config/routes.rb
Rails.application.routes.draw do
  root 'transactions#home'
  resources :transactions

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base

  def self.total
    expenses = withdrawals.reduce(0) {|sum, t| sum + t.amount}
    income = deposits.reduce(0) {|sum, t| sum + t.amount}
    income - expenses
  end

  def self.count
    self.all.count
  end

  def self.withdrawals
    self.all.select {|t| t.transaction_type == "Withdrawal"}
  end

  def self.deposits
    self.all.select {|t| t.transaction_type == "Deposit"}
  end

  def self.this_months_expenses
    expenses = withdrawals.select {|t| t.created_at.month == DateTime.now.month}
    expenses.reduce(0) {|sum, t| sum + t.amount}
  end

  def self.last_months_expenses
    expenses = withdrawals.select {|t| t.created_at.month == (DateTime.now.month - 1)}
    expenses.reduce(0) {|sum, t| sum + t.amount}
  end

  def self.count_this_month
    self.all.select {|t| t.created_at.month == DateTime.now.month}.count
  end

  def self.count_last_month
    self.all.select {|t| t.created_at.month == (DateTime.now.month - 1)}.count
  end

  def self.biggest_expense_this_month
    expenses = withdrawals.select {|t| t.created_at.month == DateTime.now.month}
    expenses.map{|t| t.amount}.sort.last
  end

  def self.biggest_expense_ever
    withdrawals.map{|t| t.amount}.sort.last
  end

  def self.money_pit
    self.where(transaction_type: "Withdrawal").group(:recipient).order("sum(amount)").last.recipient
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:edit, :update, :destroy]

  def home
    @total = Transaction.total
  end

  def index
    @transactions = Transaction.all
  end

  def new
    @transaction = Transaction.new
  end

  def edit
  end

  def create
    @transaction = Transaction.new(transaction_params)
    if @transaction.save
      redirect_to transactions_path, notice: 'Transaction was successfully created.'
    else
      render :new
    end
  end

  def update
    if @transaction.update(transaction_params)
      redirect_to transactions_path, notice: 'Transaction was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @transaction.destroy
      redirect_to transactions_url, notice: 'Transaction was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:recipient, :transaction_type, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def make_currency(amount)
    "$#{amount}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallet</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :recipient, placeholder: "Recipient" %>
  </div>
  <div class="field">
    <%= f.label :transaction_type %>
    <%= f.select :transaction_type, options_for_select(["Deposit", "Withdrawal"], "Deposit") %>
  </div>
  <div class="field">
    <%= f.number_field :amount, min: 0, placeholder: "Amount", step: 'any' %>
  </div>
  <div class="actions">
    <%= f.submit class: "button small success radius"%>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<div class="large-8 large-centered columns">
  <h1>Editing Transaction</h1>
</div>
<div class="large-4 large-centered columns">
  <%= render 'form' %>
</div>
<div class="large-4 large-centered columns" id="new-page-links">
  <%= link_to 'All Transactions', transactions_path %> |
  <%= link_to 'Home', root_path %>
</div>

app/views/transactions/home.html.erb
<div class="large-8 large-centered columns">
  <h1> Wallet Schmallet </h1>
</div>
<div class="large-8 large-centered columns">
  <% if @total < 0 %>
    <div class="welcome_bad" id="dashboard-statement">
      <div>
        You have overdrawn your account by <span class="overdrawn"><%= number_to_currency(@total*(-1)) %></span>.
        That's kind of bad.  That's really bad.
      </div>
      <div>
        THE BANK IS GOING TO CALL YOU EVERYDAY UNTIL THEY GET THEIR MONEY!!
      </div>
      <div class="fee-note">
        And also a fee...you will have to pay a fee with money you don't have!  Hooray banking!
      </div>
    </div>
  <% else %>
    <div class="welcome_good">You have <span class="positive"><%= number_to_currency(@total) %></span> in your account!</div>
  <% end %>
  <div class="large-8 large-centered columns" id="button-group">
    <div class="button-group" data-grouptype="OR">
      <%= link_to "New Transaction", new_transaction_path, class: "small button success radius" %>
      <%= link_to "List all Transactions", transactions_path, class: "small button primary radius" %>
    </div>
  </div>
</div>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<div class="large-8 large-centered columns">
  <h1>Transactions</h1>
</div>

<div class="row" id="transaction-highlights">
  <div class="large-4 columns">
    <div class="panel">
      <h5>All Transactions: <%= @transactions.count %></h5>
      <p>This Month: <%= @transactions.count_this_month %></p>
      <p>Last Month: <%= @transactions.count_last_month %></p>
    </div>
  </div>
  <div class="large-4 columns">
    <div class="panel">
      <h5>This Month's Expenses</h5>
      <p>Total Expenses: <%= number_to_currency(@transactions.this_months_expenses) %></p>
      <p>Biggest: <%= number_to_currency(@transactions.biggest_expense_this_month) %></p>
    </div>
  </div>
  <div class="large-4 centered columns">
    <div class="panel">
      <h5>Last Month's Expenses</h5>
      <p>Total Expenses: <%= number_to_currency(@transactions.last_months_expenses) %></p>
    </br>
    </div>
  </div>
</div>

<div class="row" id="biggest-expense-ever">
  <div class="large-6 columns">
    <div class="panel">
      <h5>Biggest Expense Ever</h5>
      <p><%= number_to_currency(@transactions.biggest_expense_ever) %></p>
    </div>
  </div>
  <div class="large-6 columns">
    <div class="panel">
      <h5>Money Pit</h5>
      <p><%= @transactions.money_pit %></p>
    </div>
  </div>
</div>

<div class="large-8 large-centered columns">
  <table>
    <thead>
      <tr>
        <th>Recipient</th>
        <th>Transaction Type</th>
        <th>Amount</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.recipient %></td>
          <td><%= transaction.transaction_type %></td>
          <td><%= number_to_currency(transaction.amount) %></td>
          <td><%= link_to '<i class="fa fa-pencil" title="Edit"></i>'.html_safe,
                  edit_transaction_path(transaction) %>
          </td>
          <td><%= link_to '<i class="fa fa-trash" title="Delete"></i>'.html_safe,
                  transaction, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="large-8 large-centered columns" id="button-group">
  <div class="button-group" data-grouptype="OR">
    <%= link_to "New Transaction", new_transaction_path, class: "small button success radius" %>
    <%= link_to 'Dashboard', root_path, class: "small button primary radius" %>
  </div>
</div>

app/views/transactions/new.html.erb
<div class="large-8 large-centered columns">
  <h1>New Transaction</h1>
</div>
<div class="large-4 large-centered columns">
  <%= render 'form' %>
</div>
<div class="large-4 large-centered columns" id="new-page-links">
  <%= link_to 'All Transactions', transactions_path %> |
  <%= link_to 'Home', root_path %>
</div>